version: "3"

services:
  backend:
    depends_on:
      - "postgres"
    command: "python manage.py runserver 0.0.0.0:8001"
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
