version: "3"

services:
  backend:
    depends_on:
      postgres:
        condition: 'service_healthy'

    command: "python manage.py runserver 0.0.0.0:8001"
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"

    healthcheck:
      test: 'pg_isready -h localhost -p 5432 -q -U postgres'
      interval: 3s
      timeout: 1s
      retries: 10